# Generated by Django 4.1.5 on 2023-02-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesAPI', '0002_alter_movie_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.CharField(default='none', max_length=256),
        ),
    ]
